### ISSUE TITLE
If I want to install psico, can the pymol just be a conda python module?

### ISSUE THREAD

**Issue by JonasLi-19** [speleo3/pymol-psico#22]
### Background
I'm a student using my group's Server through Xshell7. My linux system is `CentOS7` which has no GUI so I usually just use `pymol cmd` in` python scripts` to deal with files.
I know I could install VMware Ubuntu to use it or use Windows BUT those solutions takes lots of time for me to set up.
I do not want to build psico from source because that will be tricky as I am not allowed as a root user in the CentOS7 system, many dependencies couldn't be installed.
I use mamba and have already created a environment 'psico' with python=3.8 and pymol25.5 installed in this environment.

### Main question
My current main question is that how to use your `psico.modelling.mutate_all` in a python script in my conda environment 'psico', after I use mamba install speleo3::pymol-psico. 
In the README you said "add `import psico.fullinit` to `~/.pymolrc.py`", BUT I think it is not compatible for the pymol python API in a python scripts using cmd.

### My desire
My desire is to run the following code in python script to convert the whole protein dataset to mutated ones.
`psico.modelling.mutate_all(f"{base_name} and resn ASN+GLN", "LEU")`

**Comment by speleo3** [comment]
I understand that you've created an environment similar to this:
```sh
mamba create -n psicoenv schrodinger::pymol speleo3::pymol-psico
mamba activate psicoenv
```
In that environment, it should be sufficient to run `python` and execute code like this:
```py
from pymol import cmd
import psico.modelling
base_name = "1ubq"
cmd.load(f"{base_name}.pdb")
psico.modelling.mutate_all(f"{base_name} and resn ASN+GLN", "LEU")
cmd.save(f"{base_name}-mutated.pdb")
```
You don't need a `~/.pymolrc.py` file and you don't need `import psico.fullinit`. CentOS7 without GUI should be fine.
