### ISSUE TITLE
Adding USalign as a method for structural alignment

### ISSUE THREAD

**Issue by jacekzkominek** [speleo3/pymol-psico#23]
Hi, PSICO is great, thanks for creating it! I wanted to ask is there a chance to add the much more recent USalign (https://zhanggroup.org/US-align/) as an option for structural alignment? It's from the same group that created TM and MMalign, which are already included in PSICO, and it works much in the same way, so I don't expect it to be complicated.

Thanks in advance!

**Comment by speleo3** [comment]
Thanks for the request.
Implemented as new `usalign` command.

**Comment by jacekzkominek** [comment]
Thank you so much, appreciate it!

**Comment by JarrettSJohnson** [comment]
Is now native in PyMOL: https://github.com/schrodinger/pymol-open-source/commit/4769e62c02bfc629dfda6d9d62e1ea24e6db959e

**Comment by speleo3** [comment]
> Is now native in PyMOL: `schrodinger/pymol-open-source@4769e62`

very cool, thanks!
