### ISSUE TITLE
Not an issue but ..a request and a question

### ISSUE THREAD

**Issue by murpholinox** [speleo3/pymol-psico#3]
Hi. Can you please update the README.md to get the proper urls for all the programs needed?
..For example I have never listened about theseus and  google throws a lot of mythology stuff. 

And a question... What is the difference between pymol-psico and Pymol-script-repo at https://github.com/Pymol-Scripts/Pymol-script-repo.

Thanks

**Comment by speleo3** [comment]
The individual wrappers have docstrings with external URLs. E.g.:

```
PyMOL>import psico.fullinit
PyMOL>help theseus
 
DESCRIPTION
 
    Structural superposition of two molecules with maximum likelihood.
 
    THESEUS: Maximum likelihood multiple superpositioning
    http://www.theseus3d.org
```

Likewise, see:

```
PyMOL>help dssp
PyMOL>help stride
PyMOL>help tmalign
PyMOL>help dyndom
PyMOL>help prosmart
PyMOL>help dss_promotif 
```

The Pymol-script-repo is a loose collection of user-contributed scripts from various authors. **psico** is also a collection of scripts, but organized as a Python package, and (with few exceptions) written by the same person.

**Comment by murpholinox** [comment]
So... there are no scripts duplicated?
Thanks for the info....but I still think it will be better on a (separate) readme file. That way we can know beforehand what is in here ..before installing everything... (...Like I installed this repo just for the supercell.py script). (Anyway...it is just an opinion)

Thanks again

**Comment by speleo3** [comment]
yes there is functional overlap with Pymol-script-repo and some duplicated scripts. See "Already in PyMOLWiki..." column in the command list table here: https://pymolwiki.org/index.php/Psico
