### ISSUE TITLE
pymol-psico problem

### ISSUE THREAD

**Issue by Sofia-FR** [speleo3/pymol-psico#7]
Hi,
I tried to use psico, but I got the following problem: 
Traceback (most recent call last):
  File "/home/ana/.pymol/startup/xtal.py", line 238, in biomolecule
    from .importing import local_mirror_pdb
ModuleNotFoundError: No module named 'pmg_tk.startup.importing'

 how can I solve this issue?
Thank you very much!

**Comment by speleo3** [comment]
Hi @Sofia-FR -
I've updated `xtal.py` to allow using it as a standalone script. Please download it again.
