### ISSUE TITLE
Error running rmsf2b 

### ISSUE THREAD

**Issue by hypowergravity** [speleo3/pymol-psico#8]
Dear Developer, 
When I try to run rmsf2b using edited.py, I am getting the following error "Error: Must do 'import psico.editing' instead of 'run .." and I am not able to run rmsf2b calculation. I have tried to install both pymol (conda install -c schrodinger pymol) and psico (conda install -c schrodinger pymol-psico) to recent version but still I am getting the error, so kindly help me if possible. 
Thank you. 
With regards 
Sriram.

**Comment by speleo3** [comment]
As the error message says, you need to type `import psico.editing` into your script or into the PyMOL command line.

Here is a complete example:
```
fetch 1nmr
import psico.editing
rmsf2b 1nmr
```

**Comment by hypowergravity** [comment]
Though I have imported the pscico.editing, I guess there is installation or dependency problem. 
Thanks for the support.
