### ISSUE TITLE
[Feature request] Arrows for cell axes

### ISSUE THREAD

**Issue by kmdalton** [speleo3/pymol-psico#9]
Your `supercell` function is excellent. I'm using it in a course this semester! However, it is hard to tell which edge corresponds to which unit cell axis. Would it possible to add arrows corresponding to the cell axes. I'm thinking of something like [these scripts](https://pymolwiki.org/index.php/Axes) but with the cell axes as the basis rather than a cartesian basis. It would be great if it could be integrated into `xtal.py`.

**Comment by speleo3** [comment]
Good suggestion and I'm sure that it's possible. If I find some spare time, I might add it. But of course I would also accept a pull request if you think you can add it yourself.
